# Server Config
server:
    port: 7080
    servlet:
        context-path: /
        encoding:
            charset: utf-8

spring:
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mariadb://218.237.65.224:3306/modubiz
        username: root
        password: r114!@#
    jpa:
        hibernate:
            ddl-auto: update
        sql:
            init:
                platform: mariadb
mybatis:
    config-location: classpath:config/mybatis-config.xml
    mapper-locations: classpath*:mapper/**/*.xml

logging:
    level:
        jdbc:
            sqlonly: OFF
            sqltiming: INFO
            resultsettable: INFO
            audit: OFF
            resultset: OFF
            connection: OFF


# Swagger
springdoc:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    show-login-endpoint: true
    api-docs:
        groups:
            enabled: true
    swagger-ui:
        operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
        tags-sorter: alpha # 태그 정렬 기준
        path: /swagger # html 문서 접속 경로
        disable-swagger-default-url: true
        display-query-params-without-oauth2: true
        doc-expansion: none # tag, operation 펼치는 방식
    paths-to-match:
        - /**
