# Server Config
server:
    port: 7080
    servlet:
        context-path: /
        encoding:
            charset: utf-8

spring:
    profiles:
        active: mariadb

---
spring:
    config:
        activate:
            on-profile: mariadb
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: ENC(9dAVXleR/i41xMXF1c9pYlbOrHimdMMuVpyOE/LzNfso8OME/3uer5cTOfYvW1pKujm1UZPIBlXomPrBTw76sQ==)
        username: ENC(i6SvJEJeaaPJOE5OKwL8Ww==)
        password: ENC(Q+T1AzittshWhFuka2KvpGZRHvDs9oWN)
    jpa:
        hibernate:
            ddl-auto: update
        sql:
            init:
                platform: mariadb
#---
#spring:
#    config:
#        activate:
#            on-profile: mssql
#    datasource:
#        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#        url: jdbc:log4jdbc:sqlserver://222.112.162.227:1433;databasename=modubiz;encrypt=true;trustServerCertificate=true
#        username: modu
#        password: modu!@#

mybatis:
    config-location: classpath:config/mybatis-config.xml
    mapper-locations: classpath*:mapper/**/*.xml

logging:
    level:
        jdbc:
            sqlonly: OFF
            sqltiming: INFO
            resultsettable: INFO
            audit: OFF
            resultset: OFF
            connection: OFF


# Swagger
springdoc:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    show-login-endpoint: true
    api-docs:
        groups:
            enabled: true
    swagger-ui:
        operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
        tags-sorter: alpha # 태그 정렬 기준
        path: /swagger # html 문서 접속 경로
        disable-swagger-default-url: true
        display-query-params-without-oauth2: true
        doc-expansion: none # tag, operation 펼치는 방식
    paths-to-match:
        - /**

# 4ea3dc76ae748e173148548cfdb4d5feb51c6b778ad92f8a53dfa488ee7a8819